version: '2.1'

services:
  nginx:
    image: pdouble16/nginx-example:${TAG:-latest}
    mem_limit: 128m
    restart: always
    environment:
      - CONSUL_AGENT=1
      - CONSUL=consul
    ports:
      - "8080:80"


  backend:
    image: pdouble16/nginx-backend:${TAG:-latest}
    mem_limit: 128m
    restart: always
    environment:
      - CONSUL_AGENT=1
      - CONSUL=consul
    expose:
      - 3001


  consul:
    image: pdouble16/autopilotpattern-consul:1.2.0-r1
    restart: always
    mem_limit: 128m
    environment:
      - CONSUL=consul
    expose:
      - 53
      - 8300
      - 8301
      - 8302
      - 8400
      - 8500
