version: '2.1'

services:
  nginx:
    image: pdouble16/nginx-example:${TAG:-latest}
    mem_limit: 128m
    restart: always
    environment:
      - CONSUL_AGENT=1
      - ACME_ENV=staging
      - ACME_DOMAIN
      - CONSUL=nc.svc.${TRITON_CNS_SEARCH_DOMAIN_PRIVATE}
    ports:
      - 80
      - 443
      - 9090
    labels:
      - triton.cns.services=nf
    network_mode: bridge


  backend:
    image: pdouble16/nginx-backend:${TAG:-latest}
    mem_limit: 128m
    restart: always
    environment:
      - CONSUL=nc.svc.${TRITON_CNS_SEARCH_DOMAIN_PRIVATE}
    ports:
      - 3001
    labels:
      - triton.cns.services=nb
    network_mode: bridge


  consul:
    image: pdouble16/autopilotpattern-consul:1.0.6-r2
    environment:
      - CONSUL_DEV=1
    restart: always
    mem_limit: 128m
    ports:
      - 8500
    expose:
      - 53
      - 8300
      - 8301
      - 8302
      - 8400
      - 8500
    labels:
      - triton.cns.services=nc
    network_mode: bridge
